version: '3.9'
services:
  rtmp:
    build: ./live-stream
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: live_server
    volumes:
      - ./data:/tmp/hls  

  auth:
    build: ./auth
    container_name: auth_server